// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxxqxmilhcddbhyxdkxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4eHF4bWlsaGNkZGJoeXhka3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzAzODksImV4cCI6MjA2OTY0NjM4OX0.j_bEtgFgf_NUOL2LVDujEBovVT_VB2dr0Z5KwWhCnng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});